'use strict';

/*eslint max-len: ["error", { "code": 120 }]*/

const metatests = require('metatests');
const common = require('..');

metatests.case(
  'Metarhia common library',
  { common },
  {
    'common.subst': [
      ['Hello, name', { name: 'Ali' }, '', true, 'Hello, name'],
      [
        'Hello, @date@',
        { date: new Date(0) },
        '',
        true,
        'Hello, 1970-01-01 00:00',
      ],
      ['Hello, @n@', { name: 'Ali' }, '', true, 'Hello, [undefined]'],
      ['Hello, @name@', { name: null }, '', true, 'Hello, [null]'],
      [
        'Hello, @name@',
        { name: { first: 'Ali' } },
        '',
        true,
        'Hello, [object]',
      ],
      ['Hello, @name@', { name: ['Ali'] }, '', true, 'Hello, [array]'],
      ['Hello, @name@', { name: 'Ali' }, '', true, 'Hello, Ali'],
      [
        'Hello, @.name@',
        { person: { name: 'Ali' } },
        'person',
        true,
        'Hello, Ali',
      ],
      [
        '@w@, @.name@',
        { w: 'Hello', person: { name: 'Ali' } },
        'person',
        true,
        'Hello, Ali',
      ],
      ['Hello, @.value@', { name: 'Ali' }, 'name', true, 'Hello, Ali'],
      ['Hello, @username', {}, '', true, 'Hello, @username'],
      ['Hello, @name@', { name: '<Ali>' }, '', true, 'Hello, &lt;Ali&gt;'],
      ['Hello, @name@', { name: '<Ali>' }, '', false, 'Hello, <Ali>'],
    ],
    'common.section': [
      ['All you need is JavaScript', 'is', ['All you need ', ' JavaScript']],
      ['All you need is JavaScript', 'no', ['All you need is JavaScript', '']],
      ['All you need is JavaScript', 'JavaScript', ['All you need is ', '']],
      ['All you need is JavaScript', 'All', ['', ' you need is JavaScript']],
      ['All you need is JavaScript', 'a', ['All you need is J', 'vaScript']],
    ],
    'common.rsection': [
      ['All you need is JavaScript', 'is', ['All you need ', ' JavaScript']],
      ['All you need is JavaScript', 'no', ['All you need is JavaScript', '']],
      ['All you need is JavaScript', 'JavaScript', ['All you need is ', '']],
      ['All you need is JavaScript', 'All', ['', ' you need is JavaScript']],
      ['All you need is JavaScript', 'a', ['All you need is Jav', 'Script']],
    ],
    'common.split': [
      ['a,b,c,d', ',', 2, ['a', 'b']],
      ['a,b,c,d', ['a', 'b', 'c', 'd']],
      ['a;b;c;d', ';', ['a', 'b', 'c', 'd']],
      ['a,b,c,d', ';', ['a,b,c,d']],
    ],
    'common.rsplit': [
      ['a,b,c,d', ',', 2, ['c', 'd']],
      ['a,b,c,d', ['a', 'b', 'c', 'd']],
      ['a;b;c;d', ';', ['a', 'b', 'c', 'd']],
      ['a,b,c,d', ';', ['a,b,c,d']],
    ],
    'common.htmlEscape': [
      ['text', 'text'],
      ['<tag>', '&lt;tag&gt;'],
      ['You &amp; Me', 'You &amp;amp; Me'],
      ['You & Me', 'You &amp; Me'],
      ['"Quotation"', '&quot;Quotation&quot;'],
    ],
    'common.fileExt': [
      ['/dir/dir/file.txt', 'txt'],
      ['/dir/dir/file.txt', 'txt'],
      ['\\dir\\file.txt', 'txt'],
      ['/dir/dir/file.txt', 'txt'],
      ['/dir/file.txt', 'txt'],
      ['/dir/file.TXt', 'txt'],
      ['//file.txt', 'txt'],
      ['file.txt', 'txt'],
      ['/dir.ext/', 'ext'],
      ['/dir/', ''],
      ['/', ''],
      ['.', ''],
      ['', ''],
    ],
    'common.removeExt': [
      ['/dir/dir/file.txt', '/dir/dir/file'],
      ['\\dir\\file.txt', '\\dir\\file'],
      ['//file.txt', '//file'],
      ['file.txt', 'file'],
      ['/dir.ext/', '/dir'],
      ['/dir.ext/file.txt', '/dir.ext/file'],
      ['.', ''],
    ],
    'common.spinalToCamel': [
      ['hello-world', 'helloWorld'],
      ['hello_world', 'helloWorld'],
      ['one-two-three', 'oneTwoThree'],
      ['one_two_three', 'oneTwoThree'],
      ['OneTwoThree', 'OneTwoThree'],
      ['oneTwoThree', 'oneTwoThree'],
      ['hello', 'hello'],
      ['h', 'h'],
      ['-', ''],
      ['_', ''],
      ['', ''],
    ],
    'common.capitalize': [
      ['abc', 'Abc'],
      ['Abc', 'Abc'],
      ['aBC', 'Abc'],
      ['ABC', 'Abc'],
      ['a', 'A'],
      [' bc', ' Bc'],
      [' ', ' '],
      ['', ''],
      ['+', '+'],
    ],
    'common.between': [
      ['abcdefghijk', 'cd', 'h', 'efg'],
      ['field="value"', '"', '"', 'value'],
      ['field:"value"', '"', '"', 'value'],
      ['field[value]', '[', ']', 'value'],
      ['kjihgfedcba', 'cd', 'h', ''],
      ['kjihgfedcba', 'dc', 'h', ''],
      ['field="value"', '=', '=', ''],
      ['field[value]', '{', '}', ''],
      ['{a:"b",c:"d"}', '"', '"', 'b'],
      ['abcdefghijk', 'cd', 'efghijk'],
    ],
    'common.escapeRegExp': [
      [
        '/path/to/res?search=this.that&a=b',
        '\\/path\\/to\\/res\\?search=this\\.that&a=b',
      ],
      [
        '/path/to/res?search=this.that',
        '\\/path\\/to\\/res\\?search=this\\.that',
      ],
      ['/path/to/res?search', '\\/path\\/to\\/res\\?search'],
      ['/path/to/res', '\\/path\\/to\\/res'],
      ['/path', '\\/path'],
    ],
    'common.newEscapedRegExp': [
      [
        '/path/to/res?search=this.that&a=b',
        /\/path\/to\/res\?search=this\.that&a=b/g,
      ],
      ['/path/to/res?search=this.that', /\/path\/to\/res\?search=this\.that/g],
      ['/path/to/res?search', /\/path\/to\/res\?search/g],
      ['/path/to/res', /\/path\/to\/res/g],
      ['/path', /\/path/g],
    ],
    'common.addTrailingSlash': [
      ['/path', '/path/'],
      ['/path/', '/path/'],
      ['/', '/'],
      ['', '/'],
    ],
    'common.stripTrailingSlash': [
      ['/path', '/path'],
      ['/path/', '/path'],
      ['/', ''],
      ['', ''],
    ],
    'common.dirname': [
      ['/path/dir/', '/path/'],
      ['/path/dir', '/path/'],
      ['/path/', '/'],
      ['/path', '/'],
      ['/', '/'],
      ['', './'],
    ],
    'common.removeBOM': [
      ['\uBBBF\uFEFFabc', 'abc'],
      ['\uBBBF\uFEFF', ''],
      ['\uFEFFabc', 'abc'],
      ['\uBBBFabc', 'abc'],
      ['\uFEFF', ''],
      ['\uBBBF', ''],
      ['abc', 'abc'],
      [42, 42],
    ],
    'common.arrayRegExp': [
      [['*'], /^.*$/],
      [['/css/*', '/folder*'], /^((\/css\/.*)|(\/folder.*))$/],
      [['/', '/js/*'], /^((\/)|(\/js\/.*))$/],
      [['/css/*.css'], /^\/css\/.*\.css$/],
      [['*/css/*'], /^.*\/css\/.*$/],
      [[], null],
    ],
    'common.normalizeEmail': [
      ['testemail@example.com', 'testemail@example.com'],
      ['testemail@EXAMPLE.COM', 'testemail@example.com'],
      ['testemail@eXaMpLe.CoM', 'testemail@example.com'],
      ['TestEmail@example.COM', 'TestEmail@example.com'],
      ['TESTEMAIL@EXAMPLE.COM', 'TESTEMAIL@example.com'],
    ],
  }
);
